Repository EveripediaNetwork/iq-bridge-ui, pull requests merged in 2021-06, with the labels that each got.

#36 fix: avoid input special chars in the swap input
  src/components/ui/swapContainer.js
  src/features/Lock/lock.js
  src/features/Lock/lockHeader.js
  src/features/home.js
Labels: bug

#38 Feat/tx details
  package.json
  src/components/ui/txDetailsDialog.js
  src/features/Lock/lock.js
  src/features/eth.js
  src/utils/EthDataProvider/EthDataProvider.js
  src/utils/i18n.js
  yarn.lock
Labels: enhancement

#39 feat: wrong chain network dialog
  src/App.js
  src/components/layouts/layout.js
  src/components/ui/wrongChainModal.js
  src/context/chainIdProvider/chainIdContext.js
  src/features/Lock/lock.js
  src/features/eth.js
  src/features/home.js
  src/utils/i18n.js
  yarn.lock
Labels: enhancement

#47 fix: add smaller title and & fix env.template vars
  .env.template
  src/components/ui/ethereumWalletModal.js
Labels: bug

#45 Voting feature
  .env.template
  .eslintrc.json
  package.json
  src/App.js
  src/components/layouts/layout.js
  src/components/ui/cardTitle.js
  src/components/ui/genericDialog.js
  src/components/ui/proposalDetails.js
  src/components/ui/proposalsModal.js
  src/components/ui/voteBreakdown.js
  src/config.js
  src/context/proposalContext.js
  src/features/Lock/lock.js
  src/features/Voting/voting.js
  src/features/Voting/votingChart.js
  src/features/Voting/votingProposalForm.js
  src/features/eth.js
  src/features/home.js
  src/features/reverseEth.js
  src/utils/SnapshotProvider.js
  src/utils/i18n.js
  yarn.lock
Labels: enhancement

#76 fix: i18n fixes and remove unecessary code
  src/features/Voting/votingChart.js
  src/features/Voting/votingProposalForm.js
  src/utils/i18n.js
Labels: bug

#78 fix: show pie chart along with bug fixes
  src/features/Voting/voting.js
  src/utils/SnapshotProvider.js
Labels: bug

#80 Feat/handle multiple choice voting
  .env.template
  src/components/ui/proposalDetails.js
  src/components/ui/voteBreakdown.js
  src/config.js
  src/features/Voting/voting.js
  src/features/Voting/votingChart.js
  src/features/Voting/votingProposalForm.js
  src/utils/SnapshotProvider.js
Labels: enhancement

#81 refactor: move wrong chain dialog
  src/App.js
  src/components/layouts/layout.js
  src/components/ui/wrongChainModal.js
  src/context/wrongChainContext.js
  src/features/Lock/lock.js
  src/features/eth.js
  src/features/home.js
Labels: refactor
